= https://learning.oreilly.com/library/view/optimizing-java/9781492039259/[(Book) - Optimizing Java]
:toc:


== Java Performance Primer


> Mix of mathematical emperical analysis and human psycology

=== Java Performance - The Wrong Way

1. History Lesson

- For many years, a Google search for Performance Tuning in Java gave a result that was written in 1990s. That is terrible for modern Java applications where the JVM has evolved to such a point that early advices are opposite of what should be done.
- For example, in 1990s JVM has terrible method dispatch problem. This meant it was recommended to write monolith gigantic methods. But modern java has fixed the problem of method dispatch. 
- Lesson learned; Keep in mind the context of advice that you see on the internet.

2. Rule of thumb

- No magic "tricks" for JVM. Context of application is everything.
- No secret algorithms are hidden for you. In other words, there are no hidden MIRACLES.
- Statistics inference of JVM such as standard deviantion and variance are ill-suited since JVM stats are not normally distributed. 

> The observed performance measurements of JVM applications are very often not normally distributed. This means that elementary statistical techniques (e.g., standard deviation and variance) are ill-suited for handling results from JVM applications. This is because many basic statistics methods contain an implicit assumption about the normality of results distributions.

== Taxonomy of Performance


1. Throughgput
  - Defined a unit of work in soem time period.
  - 
  
2. Latency
  - Defined as time taken for complete request response
  - aka e2e time to serve arequest
  - Distributed tracing gives the latency of services in a nicroservice architecture
    - Examples: Opentelemetry (Opentracing+OpenConsensus), Jaegar, Zipkin, Datadog, Dynatrace, New Relic, Lightstep
    
3. Capacity
   - Defined as work parallism for unit of work
   - aka Parallelizability of throughput

4. Utilization 
  - CPU, Network Memory usage and other usages.


5. Scalibility
  - Linear scalability
  - Verticval vs Horizontal Scaling
6. Efficieny
  - Throughput of system/utilized resources

== JVM Overview

> JVM is a *stack-based interpreted machine*. That means, instead of using registers(like in C/C++); it uses execution stack to store partial results as well as perform operations on those elemetns on the stack.

=== What happenes inside when you run your program


1. Interpreting and Classloading

1. `java MyApplication.java` creates `MyApplication.class`
2. Entry point of `MyApplication.class` is the `main()` method
3. Java classloading happens to give control over `MyApplication.class`. For this a chain of classloaders are initialized.
  a. *Bootstrap classloader* is the initial loader. It contains classes in the core Java runtime. The main point of the *Bootstrap classloader* is to get a minimal set of classes (which includes essentials such as `java.lang.Object`, `Class`, and `Classloader`) loaded to allow other classloaders to bring up the rest of the system.
    - JDK 8 and prior: These classes are loaded from `rt.jar`
    - JDK 9 and above: Runtime is modularized and classloading is somewhat different
  b. *Extension classloader* is next created. It defines *Bootstrap clssloader* as its parent and will delegate to parent.
  c. *Application classloader* is next created. Responsible for loading user classes from the defined classpath. It defines *Extension clssloader* as its parent.
      NOTE: *Application classloader* aka *System classloader* but it is better to not use this term
4. If classes are not found by classloader (child to parent), it throws the `ClassNotFoundException`


==== Executing Bytecode

Java butecode is IR(intermediate representation) and is not tied to specific architecture. This gives it the portability across architectures.

Every class file has a specific defined structure

.Anatomy of a class file
[%header]
|===
| Component | Description| Additional information
| Magic Number| 0xCAFEBABE(JDK 8)| 0xCAFEDADA(JDK 9+) 

|Version of class file format | The minor and major versions of the class file
a| a. First 4 bytes Denotes conformance to class file format
b. Second 4 bytes Denotes major and minor version used to compile file; these are checked so that target JVM is not lower than the java used to compile the file. If this is not followed a `UnSupportedClassVersionError` is thrown @ runtime.

| Constant pool |The pool of constants for the class| for example, names of classes, interfaces, and fields. When the JVM executes code, the constant pool table is used to refer to values rather than having to rely on the layout of memory at runtime.
|Access flags |Whether the class is public, private, abstract, static, and so on
a| 1. Firt flag: identifies general properties, such as whether a class is public, followed by whether it is final and cannot be subclassed.
2. Second flag:  determines whether the class file represents an interface or an abstract class.
3. Third flag:  indicates whether the class file represents a synthetic class that is not present in source code, an annotation type, or an enum.

|This class | The name of the current class| Index to the constant pool to identify type hierarchy belonging to the class.
|Superclass |The name of the superclass| Index to the constant pool to identify type hierarchy belonging to the class.
|Interfaces |Any interfaces in the class| Index to the constant pool to identify type hierarchy belonging to the class.
|Fields|Any fields in the class| Signature-like structure includiing modifiers that apply to field
|Methods|Any methods in the class| Signature-like structure includiing modifiers that apply to method
|Attributes| Any attributes of the class (e.g., name of the source file, etc.)| Set of attributes to represent structured items not fixed in size
|===

==== Inspect `.class` file

Inspect `.class` file using `javap`

Example:

`MyApplication.java`

```java
public class MyApplication {
    public static void main(String[] args) {
        for (int i = 0; i < 10; i++) {
            System.out.println("Hello World");
        }
    }
}
```

`javap -c MyApplication`

```java
public class HelloWorld {
  public HelloWorld();
    Code:
       0: aload_0             // Places `this` reference to start of the stack
       1: invokespecial #1    //  invokes an instance method that has specific handling for calling superconstructors and creating objects. Method java/lang/Object."<init>":()V
       4: return

  public static void main(java.lang.String[]);
    Code:
       0: iconst_0    //TODO
       1: istore_1
       2: iload_1
       3: bipush        10
       5: if_icmpge     22
       8: getstatic     #2    // Field java/lang/System.out ...
      11: ldc           #3    // String Hello World
      13: invokevirtual #4    // Method java/io/PrintStream.println ...
      16: iinc          1, 1
      19: goto          2
      22: return
}
```

=== Java Hotspot VM


== Hardware and OS

== Performance Testing Patterns and Anti-patterns (Complete this after reading all other chapters and add context for each point in this chapter)


== Microbenchmarking and Statistics



== Understanding GCs


== Advanced GCs


== GC Logging, Monitoring, Tuning and Tools


== Code Execution on the JVM

== Understanding JIT Compilation

== Java Language Performance Techniques

== Concurrent Performant Techniques


== Profiling


== High-performance Logging and Messaging


== Java 9 and Future

  
